### ISSUE TITLE
Newer exchangelib >=4.7.0 changed timezone handling

### ISSUE THREAD

**Issue by smartass101** [novoid/exchange2org#22]
Thank you very much for writing this piece of code. I was very keen on trying this since I have a similar need.

However, after a fresh `pip install exchangelib` I get the following error when running the code

```bash
# config file is provided and set up correctly to the best of my knowledge
$ python exchange2org/__init__.py --calendar ~/org/calendar.org
```

```python
CRITICAL Error occured while trying to set up connection with the exchange server "......":
Traceback (most recent call last):
  File ".../exchange2org/exchange2org/__init__.py", line 426, in <module>
    main()
  File ".../exchange2org/exchange2org/__init__.py", line 413, in main
    exchange2org = Exchange2Org(exchange2orgconfig, logging.getLogger())
  File ".../exchange2org/exchange2org/__init__.py", line 158, in __init__
    self.tz = exchangelib.EWSTimeZone.timezone(self.config.TIMEZONE)
AttributeError: type object 'EWSTimeZone' has no attribute 'timezone
```
Possibly sensitive paths and URLs are redacted in the above, I hope you understand. But I don't think they have much bearing on the issue at hand.

According to the [exchangelib changelog](https://github.com/ecederstrand/exchangelib/blob/master/CHANGELOG.md#470) the `EWSTimeZone.timezone()` method has been deprecated and was removed in version `4.7.0`.

I hoped installing version `4.6.2` would fix this, which it did, but now I get

```python
.../exchange2org/exchange2org/__init__.py:158: DeprecationWarning: replace EWSTimeZone.timezone() with just EWSTimeZone()
  self.tz = exchangelib.EWSTimeZone.timezone(self.config.TIMEZONE)
.../exchange2org/exchange2org/__init__.py:314: DeprecationWarning: replace tz.localize() with dt.replace(tzinfo=tz)
  events = self.account.calendar.view(start=self.tz.localize(exchangelib.EWSDateTime(*startday)), end=self.tz.localize(exchangelib.EWSDateTime(*endday)))
Traceback (most recent call last):
  File ".../exchange2org/exchange2org/__init__.py", line 426, in <module>
    main()
  File ".../exchange2org/exchange2org/__init__.py", line 414, in main
    exchange2org.dump_calendar(startday=startday, endday=endday)
  File ".../exchange2org/exchange2org/__init__.py", line 333, in dump_calendar
    output = self.convert_to_orgmode(event)
  File ".../exchange2org/exchange2org/__init__.py", line 205, in convert_to_orgmode
    start_day = event.start.astimezone(self.tz).ewsformat()[:10]
AttributeError: 'EWSDate' object has no attribute 'astimezone'
```

So with which  last version of `exchangelib` this script worked? As a short-term solution?
Do you have plans to bring update the code to the current `exchangelib` API? As a longer-term solution.

**Comment by smartass101** [comment]
Ah, after seeing your most recent commit  yestreday https://github.com/novoid/exchange2org/commit/cfd6af60610a6d0a9ae791c8cdef986da676dac8
It appears I was just very unlucky to try this at the moment. Going back to `4.4.0` unfortunately did not fix the issue with `EWSDate`.

**Comment by novoid** [comment]
Hi,

Sorry to tell you that I haven't using the script since approximately 2019 or so.

And I don't have any access to Exchange any more (lucky me).

Therefore, I can't support this issue at the moment. I pushed cfd6af6 so that I might not get spammed of the automatically security issue version bumps. I have no idea what version was the last one I've been using. 

The message you posted looks like some changed API. Maybe the deprecated options have easy to change new options?

However, if you do find out the solution yourself, I'm happy to receive pull requests for other people to profit from your solution!
